services:
  app_api-example:
    build: ./
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://api-db:5432/api-example
      DB_USER_NAME: user
      DB_PASSWORD: 12345
    restart: on-failure
    depends_on:
      - api-db
  api-db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: api-example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"